### ISSUE TITLE
ValueError: SSD Inception V2 feature extractor 

### ISSUE THREAD

**Issue by Rub21** [Rub21/tensorflow-building-detection#1]
```
root@9fde0a851fe0:/usr/src/app/models/research/object_detection# python train.py --logtostderr              --train_dir=training/              --pipeline_config_path=training/ssd_inception_v2_coco.config
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/usr/src/app/models/research/object_detection/trainer.py", line 240, in train
    detection_model = create_model_fn()
  File "/usr/src/app/models/research/object_detection/builders/model_builder.py", line 98, in build
    add_background_class)
  File "/usr/src/app/models/research/object_detection/builders/model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "/usr/src/app/models/research/object_detection/builders/model_builder.py", line 138, in _build_ssd_feature_extractor
    override_base_feature_extractor_hyperparams)
  File "/usr/src/app/models/research/object_detection/models/ssd_inception_v2_feature_extractor.py", line 68, in __init__
    raise ValueError('SSD Inception V2 feature extractor always uses'
ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.
```

**Comment by Rub21** [comment]
This was resolved by this commit : https://github.com/developmentseed/label-maker/commit/94f1863945c47e1b69fe0d6d575caa0b42aa8d63

Thank you @Geoyi!!

**Comment by narottaman** [comment]
@Rub21 
even i'm facing the same prblm! can you pls explain how did you solved it.....?

**Comment by Geoyi** [comment]
Check out the above comment that @Rub21 mentioned, or go here (https://github.com/developmentseed/label-maker/blob/94f1863945c47e1b69fe0d6d575caa0b42aa8d63/examples/utils/ssd_inception_v2_coco.config) to pull down a new updated ssd_inception_v2_coco.config @narottaman

**Comment by narottaman** [comment]
thanks @Geoyi 
the problem is solved!

**Comment by nguyendptse62666** [comment]
> Check out the above comment that @Rub21 mentioned, or go here (https://github.com/developmentseed/label-maker/blob/94f1863945c47e1b69fe0d6d575caa0b42aa8d63/examples/utils/ssd_inception_v2_coco.config) to pull down a new updated ssd_inception_v2_coco.config @narottaman

Thank you @Geoyi 
@Rub21 Line 101 it work for me.

**Comment by SundarML** [comment]
@Geoyi  I am facing this error...any solution, Thanks.
ValueError: ssd_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by AshishGusain17** [comment]
> @Geoyi I am facing this error...any solution, Thanks.
> ValueError: ssd_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

Hey I am facing same error, have you solved it.
Tensorflow version 1.15.2
Using google colab

**Comment by charleneolive** [comment]
> @Geoyi I am facing this error...any solution, Thanks.
> ValueError: ssd_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

I am facing this too. Have you solved it?

**Comment by ademkesim** [comment]
@Charlene9698 @AshishGusain17 @Geoyi Have you solved it?

**Comment by AshishGusain17** [comment]
> @Charlene9698 @AshishGusain17 @Geoyi Have you solved it?
try tf2 models

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

**Comment by ademkesim** [comment]
@AshishGusain17 Thank you. I will try

**Comment by charleneolive** [comment]
Thank you so much!! @AshishGusain17 , I will try too
